### DISCUSSION TITLE
Adding multiple (quantity, unit_cost) to a lot

### DISCUSSION THREAD

**Discussion by alt-romes** [achannarasappa/ticker#138] [Q&A] [answered]
Hello, is there a supported way to add multiple quantities to a lot?
For example:
```
- symbol: "AAPL"
   quantity: 5
   unit_cost: 100
   quantity: 10
   unit_cost: 90
```

If there is, it would be nice to include it in the readme :)

**Comment by achannarasappa** [comment, marked as answer]
Yes this is included in the example:

```
lots:
  - symbol: "ABNB"
    quantity: 35.0
    unit_cost: 146.00
  - symbol: "ARKW"
    quantity: 20.0
    unit_cost: 152.25
  - symbol: "ARKW"
    quantity: 20.0
    unit_cost: 145.35
```

Is there a way you'd suggest to make this clearer?
