### ISSUE TITLE
Panic in current version

### ISSUE THREAD

**Issue by viperperidot** [achannarasappa/ticker#132]
```
Caught panic:

runtime error: slice bounds out of range [6:2]

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack(0x56, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.15.8/x64/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
	/opt/hostedtoolcache/go/1.15.8/x64/src/runtime/debug/stack.go:16 +0x25
github.com/charmbracelet/bubbletea.(*Program).Start.func1(0xc000137140)
	/home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.12.2/tea.go:119 +0xd3
panic(0x95ada0, 0xc00017e1e0)
	/opt/hostedtoolcache/go/1.15.8/x64/src/runtime/panic.go:969 +0x1b9
github.com/charmbracelet/bubbles/viewport.Model.visibleLines(...)
	/home/runner/go/pkg/mod/github.com/charmbracelet/bubbles@v0.7.5/viewport/viewport.go:79
github.com/charmbracelet/bubbles/viewport.Model.View(0x50, 0x15, 0x6, 0x0, 0x0, 0xc00025a020, 0x2, 0x2, 0x1c5, 0x0)
	/home/runner/go/pkg/mod/github.com/charmbracelet/bubbles@v0.7.5/viewport/viewport.go:364 +0x24b
github.com/achannarasappa/ticker/internal/ui.Model.View(0x5, 0xc0000d0870, 0x5, 0x5, 0xc00015a000, 0x6, 0x6, 0x101010101, 0x0, 0x0, ...)
	/home/runner/work/ticker/ticker/internal/ui/ui.go:143 +0xc5
:~$ ^Cbletea.(*Program).Start(0xc000137140, 0x0, 0x0)
:~$ g/mod/github.com/charmbracelet/bubbletea@v0.12.2/tea.go:216 +0x67d
github.com/achannarasappa/ticker/internal/ui.Start.func1(0x0, 0x0)
	/home/runner/work/ticker/ticker/internal/ui/start.go:14 +0x1b6
github.com/achannarasappa/ticker/internal/cli.Run.func1(0xcf6ac0, 0xd31c88, 0x0, 0x0)
	/home/runner/work/ticker/ticker/internal/cli/cli.go:35 +0x2a
github.com/spf13/cobra.(*Command).execute(0xcf6ac0, 0xc0000961b0, 0x0, 0x0, 0xcf6ac0, 0xc0000961b0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xcf6ac0, 0x44570a, 0xcae140, 0xc000042778)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/achannarasappa/ticker/cmd.Execute()
	/home/runner/work/ticker/ticker/cmd/root.go:33 +0x31
main.main()
	/home/runner/work/ticker/ticker/main.go:6 +0x25


```

**Comment by achannarasappa** [comment]
@viperperidot thanks for reporting this

Would you be able to provide an example `.ticker.yaml` file to help replicate this?

**Comment by viperperidot** [comment]
Sure
```
# ~/.ticker.yaml
show-tags: true
show-fundamentals: true
show-separator: true
show-summary: true
show-holdings: true
interval: 5
sort: user
currency: XXX
watchlist:
  - 
lots:
  - symbol: "X"
    quantity: X
    unit_cost: X
  - symbol: "X"
    quantity: X
    unit_cost: X
  - symbol: "X"
    quantity: X
    unit_cost: X
  - symbol: "X"
    quantity: X
    unit_cost: X
  - symbol: "X"
    quantity: X
    unit_cost: X
  - symbol: "X"
    quantity: X
    unit_cost: X
  - symbol: "X"
    quantity: X
    unit_cost: X
  - symbol: "X"
    quantity: X
    unit_cost: X
```
I just X'ed everything out for privacy but thats basically it, using the format shown in the readme.

**Comment by achannarasappa** [comment]
Would it be possible to provide a anonymized/minimal version of your config? For example, this config based off of your example works okay for me:

```
show-tags: true
show-fundamentals: true
show-separator: true
show-summary: true
show-holdings: true
interval: 5
sort: user
currency: EUR
watchlist:
  - NET
lots:
  - symbol: "F"
    quantity: 20.0
    unit_cost: 152.25
    ```
