### ISSUE TITLE
Feature request: Provide "sell" option for lots to calculate average cost

### ISSUE THREAD

**Issue by spsx** [achannarasappa/ticker#152]
**Problem Statement**
Is your feature request related to a problem? Please describe.

If I sell part of a stock being tracked on Ticker (with multiple lots for the same symbol), I want Ticker to be able to recompute the average cost automatically. Right now I have to perform the calculation by hand and then input the adjusted unit cost and quantity.

**Proposed Solution**

We have:

```
lots:
  - symbol: "ABC"
    quantity: 100
    unit_cost: 50
  - symbol: "ABC"
    quantity: 100
    unit_cost: 40
```

We sell 50 units of ABC at $60. Right now I have to calculate the adjusted cost and quantity myself and then input it into Ticker. It would be nice to have something like:

```
sells:
  - symbol: "ABC"
    quantity: 50
    unit_cost: 60
```

Where we tell Ticker we have sold part of that stock, and Ticker will recompute our total quantity and average cost.

**Alternatives**

N/A

**Use Cases**

N/A

**Additional context**

N/A
