### ISSUE TITLE
Color displayed differently with and without tmux

### ISSUE THREAD

**Issue by ngocphamm** [achannarasappa/ticker#184]
**Describe the bug**
I really don't know if this is a bug, and I think it's not likely. I just noticed some small differences in colors when using `ticker` inside tmux, and I'm not sure what's supposed to be the "correct" one.

**To Reproduce**
1. Start `ticker` in an iTerm2 session
2. Start `ticker` in another iTerm2 session, with tmux
3. See differences

**Screenshots**
Without tmux
![CleanShot 2021-07-02 at 14 26 54](https://user-images.githubusercontent.com/395123/124315176-8ecba500-db41-11eb-81ee-48515cd5bb1b.png)

With tmux
![CleanShot 2021-07-02 at 14 17 30](https://user-images.githubusercontent.com/395123/124315061-60e66080-db41-11eb-870a-73bc2a6acfb3.png)

**Environment (please complete the following information):**
 - OS: macOS
 - Terminal: iTerm
 - Terminal Version: 3.4.8
 - Font: (Optional) Cascadia Code
 - ticker Version: 4.2.0

**Additional context**
I *think* both iTerm2 itself, and tmux support True Color, and just that the 2 report a different `$TERM` (see the lower parts of the 2 screenshot).

iTerm2 -> `$TERM = xterm-256color`
tmux -> `$TERM = screen-256color`. This is due to `nvim`'s `:checkhealth`  complaining about the `$TERM` should be `screen-256color`
![CleanShot 2021-07-02 at 14 32 40](https://user-images.githubusercontent.com/395123/124315780-77d98280-db42-11eb-9273-b1a034e7581c.png)

`.config/ticker.yaml` - made up numbers
```
show-summary: true
show-tags: true
show-fundamentals: true
show-separator: true
show-holdings: true
sort: "alpha"
interval: 15
currency: USD
watchlist:
  - AAPL
lots:
  - symbol: "AAPL"
    quantity: 4
    unit_cost: 123.45
  - symbol: "AMD"
    quantity: 3
    unit_cost: 67.89
  - symbol: "SHOP"
    quantity: 2
    unit_cost: 1234.56
  - symbol: "SONO"
    quantity: 1
    unit_cost: 45.67
```
