### ISSUE TITLE
(feature request) show profits/loss percent based on "lots"

### ISSUE THREAD

**Issue by GETandSELECT** [achannarasappa/ticker#20]
Hi

Thank you very much for this software. At the moment I use the _Stocks.app_ from Apple, which unfortunately has a proprietary file format. YAML is much better. The first impression of your software has me excited.

Example config:

```
show-tags: true
show-fundamentals: true
show-separator: true
interval: 10
watchlist:
  - BTC-EUR
lots:
  - symbol: "BTC-EUR"
    quantity: 0.24
    unit_cost: 900
```

Let's suppose I bought 0.24 Bitcoin for 900 Euro in the past.
I now wish to see how much profit or loss I made (in percent) with today price.

I am absolutely new to the investing world, but this profit/loss percent interests me the most.
