### ISSUE TITLE
Watchlist is now showing up in all group tabs

### ISSUE THREAD

**Issue by ajgringo619** [achannarasappa/ticker#214]
**Describe the bug**
Watch lists are no longer separated by group; this is even present using the sample .yaml.

**To Reproduce**
1. Start with options:
```
show-summary: true
show-tags: false
show-fundamentals: true
show-separator: true
show-holdings: true
sort: value
interval: 10
currency: USD
currency-summary-only: false
```
**Expected behavior**
Watch lists should stay separated by group if configured that way.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [Linux]
 - Terminal: [gnome-terminal]
 - Terminal Version: [3.42.2]
 - ticker Version: [v4.5.0]

**Additional context**
Here's my (abbreviated) .yaml file:
```
groups:
  - name: crypto
    watchlist:
      - CURE-USD
      - DOGE-USD
      - LINK-USD
      - LTC-USD
      - MANA-USD
      - MATIC-USD
      - MKR-USD
      - SOL-USD
      - TRX-USD
      - YFI-USD
      - ZRX-USD

    holdings:
      - symbol: "ADA-USD"
        quantity: xxxxx
        unit_cost: xxxxx

      - symbol: "BTC-USD"
        quantity: xxxxx
        unit_cost: xxxxx

  - name: stocks
    watchlist:
      - CTIC
      - ERF
      - HLMN
      - INDI
      - KNTNF
      - PSFE
      - ROVR
      - SFT
    holdings:
      - symbol: "ACHL"
        quantity: xxxxx
        unit_cost: xxxxx

      - symbol: "BTG"
        quantity: xxxxx
        unit_cost: xxxxx
```
