### ISSUE TITLE
total change wrong with disable-unit-cost-conversion

### ISSUE THREAD

**Issue by jeremyrgreen** [achannarasappa/ticker#241]
**Describe the bug**
When `currency-disable-unit-cost-conversion` is set to `true`, the average unit cost is treated correctly as being in my local currency. However, the total change in value of the holding is computed as if this were in the foreign currency.

**To Reproduce**
Here's a minimal example config file showing the outcome, using a JPY->EUR conversion to make the effect clear:
```
show-tags: true
show-holdings: true
currency: EUR
currency-disable-unit-cost-conversion: true
watchlist:
lots:
  - symbol: 7974.T
    quantity: 1
    unit_cost: 37
```

**Expected behavior**
In this example, the unit cost of 37 EUR is close to the market price, so there should be a small total change. However, it is treated as 37 JPY and re-converted to EUR, so the total change shown is almost as large as the current value of the holding.

**Environment**
 - OS: Fedora 37
 - ticker Version: 4.5.5
