### ISSUE TITLE
Holdings ignored when using CoinGecko

### ISSUE THREAD

**Issue by ajgringo619** [achannarasappa/ticker#245]
**Describe the bug**
When using CoinGecko as a data source, the ticker prices are being retrieved, but the holdings are being ignored

**To Reproduce**
1. Switch from Yahoo! to CoinGecko
3. Start ticker
4. Get no holdings data

**Expected behavior**
Data source should not affect holdings calculations

**Screenshots**
![ticker-coingecko](https://user-images.githubusercontent.com/53413561/220208725-b99794a9-2e32-430c-bfd2-df890f9975f9.jpg)

**Environment (please complete the following information):**
 - OS: Linux
 - Terminal: xfce4-terminal
 - ticker Version: v4.5.6

**Additional context**
Here is how my holdings config looks:
```
- holdings:
  - quantity: N/A
    symbol: CARDANO.CG
    unit_cost: N/A
  - quantity: N/A
    symbol: KAVA-USD
    unit_cost: N/A
```
