### ISSUE TITLE
Error: invalid config: No watchlist provided

### ISSUE THREAD

**Issue by accforgithubtest** [achannarasappa/ticker#261]
I am trying to use ticker via docker, and have mounter the required .ticker.yaml as a volume mapping.
I still get the below error while the container starts up.

```
Error: invalid config: No watchlist provided
invalid config: No watchlist provided
Usage:
  ticker [flags]
  ticker [command]
Available Commands:
  completion  Generate the autocompletion script for the specified shell
  help        Help about any command
  print       Prints holdings
Flags:
      --config string       config file (default is $HOME/.ticker.yaml)
  -h, --help                help for ticker
  -i, --interval int        refresh interval in seconds
      --proxy string        proxy URL for requests (default is none)
      --show-fundamentals   display open price, high, low, and volume for each quote
      --show-holdings       display average unit cost, quantity, portfolio weight
      --show-separator      layout with separators between each quote
      --show-summary        display summary of total gain and loss for positions
      --show-tags           display currency, exchange name, and quote delay for each quote
      --sort string         sort quotes on the UI. Set "alpha" to sort by ticker name. Set "value" to sort by position value. Keep empty to sort according to change percent
  -v, --version             version for ticker
  -w, --watchlist string    comma separated list of symbols to watch
Use "ticker [command] --help" for more information about a command.
```

For now I am only using the example file provided in the readme
```
# ~/.ticker.yaml
show-summary: true
show-tags: true
show-fundamentals: true
show-separator: true
show-holdings: true
interval: 5
currency: USD
currency-summary-only: false
watchlist:
  - NET
  - TEAM
  - ESTC
  - BTC-USD
  - SOL.X # Solana price via CoinGecko
  - SAMOYEDCOIN.CG # Samoyed price via CoinGecko
lots:
  - symbol: "ABNB"
    quantity: 35.0
    unit_cost: 146.00
  - symbol: "ARKW"
    quantity: 20.0
    unit_cost: 152.25
  - symbol: "ARKW"
    quantity: 20.0
    unit_cost: 145.35
    fixed_cost: 7.00 # e.g. brokerage commission fee
groups:
  - name: crypto
    watchlist:
      - SHIB-USD
      - VGX-USD
    holdings:
      - symbol: SOL1-USD
        quantity: 17
        unit_cost: 159.10
```
