### ISSUE TITLE
Configuration from the readme does not work with the ticker. 

### ISSUE THREAD

**Issue by webgtx** [achannarasappa/ticker#272]
**Describe the bug**
Configuration from the readme does not work with the ticker. 

**To Reproduce**
1. Build ticker
3. Copy config from the readme to `~/.ticker.yaml`
4. Run `ticker --config ~/.ticker.yaml`
5. See following error `invalid config: yaml: line 2: mapping values are not allowed in this context`

**Expected behavior**
Anything but error

**Environment (please complete the following information):**
 - OS: `Fedora release 40 (Forty)`
 - Terminal: `foot version: 1.17.2 -pgo +ime +graphemes -assertions`
 - ticker Version: ticker version v0.0.0 (I built it on latest git commit)

**Configuration that I'm using**
The place where I get it from: https://github.com/achannarasappa/ticker#configuration
```yaml
i# ~/.ticker.yaml
show-summary: true
show-tags: true
show-fundamentals: true
show-separator: true
show-holdings: true
interval: 5
currency: USD
currency-summary-only: false
watchlist:
  - NET
  - TEAM
  - ESTC
  - BTC-USD # Bitcoin price via Yahoo
  - SOL.X # Solana price via CoinGecko
  - SAMOYEDCOIN.CG # Samoyed price via CoinGecko
  - CARDANO.CC # Samoyed price via CoinCap
lots:
  - symbol: "ABNB"
    quantity: 35.0
    unit_cost: 146.00
  - symbol: "ARKW"
    quantity: 20.0
    unit_cost: 152.25
  - symbol: "ARKW"
    quantity: 20.0
    unit_cost: 145.35
    fixed_cost: 7.00 # e.g. brokerage commission fee
groups:
  - name: crypto
    watchlist:
      - SHIB-USD
      - VGX-USD
    holdings:
      - symbol: SOL1-USD
        quantity: 17
        unit_cost: 159.10
```
