### ISSUE TITLE
fixed_cost value does not accumulate

### ISSUE THREAD

**Issue by diogoftm** [achannarasappa/ticker#283]
For multiple entries under `lots` with the same symbol, only the first `fixed_cost` is being considered. This has two implications, first the value of `fixed_cost` does not accumulate for the same symbol and, second, if `fixed_cost` is only introduced in the second or later instance of a symbol in the `lots`, its value is completly ignored.

**To Reproduce**
Using this configuration that is basically the one in the `README.md`:
```yml
lots:
  - symbol: "ARKW"
    quantity: 20.0
    unit_cost: 100
  - symbol: "ARKW"
    quantity: 20.0
    unit_cost: 100
    fixed_cost: 7.00
```

The cost displayed is 4000 instead of the expected 4007.

Also, if using this configuration:
```yaml
lots:
  - symbol: "ABNB"
    quantity: 35.0
    unit_cost: 100.00
    fixed_cost: 2.00
  - symbol: "ABNB"
    quantity: 70.0
    unit_cost: 50.00
    fixed_cost: 3.00
```

The cost that is displayed is 7002 instead of 7005.

**Expected behavior**
`fixed_cost` of all entries under `lots` should be considered and accumulate across multiple entries for the same symbol. 

**Environment:**
 - ticker Version: v4.7.1

**Possible solution**

Change line 160 in `asset.go` from:
````go
aggregatedLot.Cost += lot.Quantity * lot.UnitCost
````

to:
```go
aggregatedLot.Cost += lot.Quantity*lot.UnitCost + lot.FixedCost
```
