### ISSUE TITLE
Feature request: Groups

### ISSUE THREAD

**Issue by JustinAiken** [achannarasappa/ticker#99]
**Problem Statement**
Differing investments - larger long-term crypto holdings vs day-traded weed stocks are all grouped and sorted together

**Proposed Solution**
- Each lot (or watched stock) can be assigned to a group
- Each group gets their own summary
- Groups are sorted as defined in config file
 
**Alternatives**
A tabbed view as described in #94 might also be nice

**Comment by MateuszPu** [comment]
I think the temporary workaround for this problem is creating multiple config files and run ticker with --config command.
ex:
ticker --config myportfolio1.yml
ticker --config myportfolio2.yml
ticker --config myportfolio3.yml

**Comment by Aqualie** [comment]
This would be a nice feature to have in the config we could possibly add a new option for each ticker to define the association to various groups, if this configuration is missing then they would be grouped under a "Default" group section.
```
watchlist:
  - ticker: NET
    group: B
  - ticker: TEAM
    group: B
  - ticker: ESTC
     group: A
  - ticker: BTC-USD

```

In the UI I think the tab idea would look the best given the current UI layout to represent the groups.
